<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_mail().
 */
function config_patch_gitlab_mail($key, &$message, $params) {
  if ($key == 'send_patch') {
    $message['from'] = $params['ident'];
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['message'];
    $message['params']['files'] = $params['attachments'];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Add extra fields to patch submission form.
 */
function config_patch_gitlab_form_config_patch_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['mr_message'] = [
    '#type' => 'textarea',
    '#description' => t('Additional description for this merge request.'),
  ];
}
