name: 'Config Patch Gitlab'
type: module
description: 'Send patches to Gitlab as MRs'
core_version_requirement: ^8 || ^9
package: 'Config'
configure: config_patch_gitlab.settings
dependencies:
  - config_patch:config_patch
  - swiftmailer:swiftmailer
  - mailsystem:mailsystem