<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function config_patch_gitlab_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the config_patch_gitlab module.
    case 'help.page.config_patch_gitlab':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('config_patch plugin to create merge requests on Gitlab') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_mail().
 */
function config_patch_gitlab_mail($key, &$message, $params) {
  if ($key == 'send_patch') {
    $message['from'] = $params['from'];
    $message['subject'] = $params['subject'];
    $message['body'][] = $params['message'];
    $message['params']['files'] = $params['attachments'];
  }
}
