config_patch_gitlab.settings:
  type: config_object
  label: 'Config patch Gitlab settings'
  mapping:
    email:
      type: string
      label: 'Email address for sending patches'
    append_message:
      type: string
      label: 'Message to append to all MRs'
    mr_list_link:
      type: string
      label: 'URL to MRs in repo'